/* doupload.h
   Generated by wsdl2h 2.8.23 from http://172.22.62.238/UpdateStudentStatus.asmx?WSDL and typemap.dat
   2015-09-02 02:46:02 GMT

   DO NOT INCLUDE THIS FILE DIRECTLY INTO YOUR PROJECT BUILDS
   USE THE soapcpp2-GENERATED SOURCE CODE FILES FOR YOUR PROJECT BUILDS

   gSOAP XML Web services tools.
   Copyright (C) 2000-2015 Robert van Engelen, Genivia Inc. All Rights Reserved.
   Part of this software is released under one of the following licenses:
   GPL or Genivia's license for commercial use.
*/

/** @page page_notes Notes

@note HINTS:
 - Run soapcpp2 on doupload.h to generate the SOAP/XML processing logic.
   Use soapcpp2 -I to specify paths for #import
   To build with STL, 'stlvector.h' is imported from 'import' dir in package.
   Use soapcpp2 -j to generate improved proxy and server classes.
 - Use wsdl2h -c and -s to generate pure C code or C++ code without STL.
 - Use 'typemap.dat' to control namespace bindings and type mappings.
   It is strongly recommended to customize the names of the namespace prefixes
   generated by wsdl2h. To do so, modify the prefix bindings in the Namespaces
   section below and add the modified lines to 'typemap.dat' to rerun wsdl2h.
 - Use Doxygen (www.doxygen.org) on this file to generate documentation.
 - Use wsdl2h -R to generate REST operations.
 - Use wsdl2h -nname to use name as the base namespace prefix instead of 'ns'.
 - Use wsdl2h -Nname for service prefix and produce multiple service bindings
 - Use wsdl2h -d to enable DOM support for xsd:anyType.
 - Use wsdl2h -g to auto-generate readers and writers for root elements.
 - Use wsdl2h -b to auto-generate bi-directional operations (duplex ops).
 - Use wsdl2h -U to map XML names to C++ Unicode identifiers instead of _xNNNN.
 - Use wsdl2h -u to disable the generation of unions.
 - Struct/class members serialized as XML attributes are annotated with a '@'.
 - Struct/class members that have a special role are annotated with a '$'.

@warning
   DO NOT INCLUDE THIS ANNOTATED FILE DIRECTLY IN YOUR PROJECT SOURCE CODE.
   USE THE FILES GENERATED BY soapcpp2 FOR YOUR PROJECT'S SOURCE CODE:
   THE soapStub.h FILE CONTAINS THIS CONTENT WITHOUT ANNOTATIONS.

@copyright LICENSE:
@verbatim
--------------------------------------------------------------------------------
gSOAP XML Web services tools
Copyright (C) 2000-2015, Robert van Engelen, Genivia Inc. All Rights Reserved.

This software is released under one of the following licenses:
GPL or Genivia's license for commercial use.
--------------------------------------------------------------------------------
GPL license.

This program is free software; you can redistribute it and/or modify it under
the terms of the GNU General Public License as published by the Free Software
Foundation; either version 2 of the License, or (at your option) any later
version.

This program is distributed in the hope that it will be useful, but WITHOUT ANY
WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS FOR A
PARTICULAR PURPOSE. See the GNU General Public License for more details.

You should have received a copy of the GNU General Public License along with
this program; if not, write to the Free Software Foundation, Inc., 59 Temple
Place, Suite 330, Boston, MA 02111-1307 USA

Author contact information:
engelen@genivia.com / engelen@acm.org

This program is released under the GPL with the additional exemption that
compiling, linking, and/or using OpenSSL is allowed.
--------------------------------------------------------------------------------
A commercial-use license is available from Genivia, Inc., contact@genivia.com
--------------------------------------------------------------------------------
@endverbatim

*/


//gsoapopt w

/******************************************************************************\
 *                                                                            *
 * Definitions                                                                *
 *   JF.ClassRoomGuidance.Webservice                                          *
 *                                                                            *
\******************************************************************************/


/******************************************************************************\
 *                                                                            *
 * Import                                                                     *
 *                                                                            *
\******************************************************************************/


/******************************************************************************\
 *                                                                            *
 * Schema Namespaces                                                          *
 *                                                                            *
\******************************************************************************/


/* NOTE:

It is strongly recommended to customize the names of the namespace prefixes
generated by wsdl2h. To do so, modify the prefix bindings below and add the
modified lines to typemap.dat to rerun wsdl2h:

ns1 = "JF.ClassRoomGuidance.Webservice"

*/

#define SOAP_NAMESPACE_OF_ns1	"JF.ClassRoomGuidance.Webservice"
//gsoap ns1   schema namespace:	JF.ClassRoomGuidance.Webservice
//gsoap ns1   schema elementForm:	qualified
//gsoap ns1   schema attributeForm:	unqualified

/******************************************************************************\
 *                                                                            *
 * Built-in Schema Types and Top-Level Elements and Attributes                *
 *                                                                            *
\******************************************************************************/


/******************************************************************************\
 *                                                                            *
 * Forward Declarations                                                       *
 *                                                                            *
\******************************************************************************/


//  Forward declaration of class _ns1__UpdateClassRoomPersonStatus.
class _ns1__UpdateClassRoomPersonStatus;

//  Forward declaration of class _ns1__UpdateClassRoomPersonStatusResponse.
class _ns1__UpdateClassRoomPersonStatusResponse;


/******************************************************************************\
 *                                                                            *
 * Schema Types and Top-Level Elements and Attributes                         *
 *   JF.ClassRoomGuidance.Webservice                                          *
 *                                                                            *
\******************************************************************************/


/******************************************************************************\
 *                                                                            *
 * Schema Complex Types and Top-Level Elements                                *
 *   JF.ClassRoomGuidance.Webservice                                          *
 *                                                                            *
\******************************************************************************/

/// @brief Top-level root element "JF.ClassRoomGuidance.Webservice":UpdateClassRoomPersonStatus
/// @brief "JF.ClassRoomGuidance.Webservice":UpdateClassRoomPersonStatus is a complexType.
///
/// class _ns1__UpdateClassRoomPersonStatus operations:
/// - soap_new__ns1__UpdateClassRoomPersonStatus(soap*) allocate
/// - soap_new__ns1__UpdateClassRoomPersonStatus(soap*, int num) allocate array
/// - soap_new_req__ns1__UpdateClassRoomPersonStatus(soap*, ...) allocate, set required members
/// - soap_new_set__ns1__UpdateClassRoomPersonStatus(soap*, ...) allocate, set all public members
/// - int soap_read__ns1__UpdateClassRoomPersonStatus(soap*, _ns1__UpdateClassRoomPersonStatus*) deserialize from a stream
/// - int soap_write__ns1__UpdateClassRoomPersonStatus(soap, _ns1__UpdateClassRoomPersonStatus*) serialize to a stream
class _ns1__UpdateClassRoomPersonStatus
{ public:
/// Element "account" of XSD type xs:string.
    char*                                account                        0;	///< Optional element.
/// Element "password" of XSD type xs:string.
    char*                                password                       0;	///< Optional element.
/// Element "roomNo" of XSD type xs:string.
    char*                                roomNo                         0;	///< Optional element.
/// Element "studentCount" of XSD type xs:int.
    int                                  studentCount                   1;	///< Required element.
/// Element "updateTime" of XSD type xs:dateTime.
    time_t                               updateTime                     1;	///< Required element.
/// A handle to the soap struct that manages this instance (automatically set).
    struct soap                         *soap                          ;
};

/// @brief Top-level root element "JF.ClassRoomGuidance.Webservice":UpdateClassRoomPersonStatusResponse
/// @brief "JF.ClassRoomGuidance.Webservice":UpdateClassRoomPersonStatusResponse is a complexType.
///
/// class _ns1__UpdateClassRoomPersonStatusResponse operations:
/// - soap_new__ns1__UpdateClassRoomPersonStatusResponse(soap*) allocate
/// - soap_new__ns1__UpdateClassRoomPersonStatusResponse(soap*, int num) allocate array
/// - soap_new_req__ns1__UpdateClassRoomPersonStatusResponse(soap*, ...) allocate, set required members
/// - soap_new_set__ns1__UpdateClassRoomPersonStatusResponse(soap*, ...) allocate, set all public members
/// - int soap_read__ns1__UpdateClassRoomPersonStatusResponse(soap*, _ns1__UpdateClassRoomPersonStatusResponse*) deserialize from a stream
/// - int soap_write__ns1__UpdateClassRoomPersonStatusResponse(soap, _ns1__UpdateClassRoomPersonStatusResponse*) serialize to a stream
class _ns1__UpdateClassRoomPersonStatusResponse
{ public:
/// Element "UpdateClassRoomPersonStatusResult" of XSD type xs:int.
    int                                  UpdateClassRoomPersonStatusResult 1;	///< Required element.
/// A handle to the soap struct that manages this instance (automatically set).
    struct soap                         *soap                          ;
};


/******************************************************************************\
 *                                                                            *
 * Additional Top-Level Elements                                              *
 *   JF.ClassRoomGuidance.Webservice                                          *
 *                                                                            *
\******************************************************************************/


/******************************************************************************\
 *                                                                            *
 * Additional Top-Level Attributes                                            *
 *   JF.ClassRoomGuidance.Webservice                                          *
 *                                                                            *
\******************************************************************************/


/******************************************************************************\
 *                                                                            *
 * Services                                                                   *
 *                                                                            *
\******************************************************************************/

// This service supports SOAP 1.2 namespaces:
#import "soap12.h"

//gsoap ns1  service name:	UpdateStudentStatusSoap 
//gsoap ns1  service type:	UpdateStudentStatusSoap 
//gsoap ns1  service port:	http://172.22.62.238/UpdateStudentStatus.asmx 
//gsoap ns1  service namespace:	JF.ClassRoomGuidance.Webservice 
//gsoap ns1  service transport:	http://schemas.xmlsoap.org/soap/http 

/** @mainpage Service Definitions

@section Service_bindings Service Bindings

  - @ref UpdateStudentStatusSoap

@section Service_more More Information

  - @ref page_notes "Notes"

  - @ref page_XMLDataBinding "XML Data Binding"

  - @ref SOAP_ENV__Header "SOAP Header Content" (when applicable)

  - @ref SOAP_ENV__Detail "SOAP Fault Detail Content" (when applicable)


*/

/**

@page UpdateStudentStatusSoap Binding "UpdateStudentStatusSoap"

@section UpdateStudentStatusSoap_operations Operations of Binding "UpdateStudentStatusSoap"

  - @ref __ns1__UpdateClassRoomPersonStatus

  - @ref __ns1__UpdateClassRoomPersonStatus_

@section UpdateStudentStatusSoap_ports Endpoints of Binding "UpdateStudentStatusSoap"

  - http://172.22.62.238/UpdateStudentStatus.asmx

@note Multiple service bindings collected as one, use wsdl2h option -Nname to produce a separate service for each binding


*/

/******************************************************************************\
 *                                                                            *
 * Service Binding                                                            *
 *   UpdateStudentStatusSoap                                                  *
 *                                                                            *
\******************************************************************************/


/******************************************************************************\
 *                                                                            *
 * Service Operation                                                          *
 *   __ns1__UpdateClassRoomPersonStatus                                       *
 *                                                                            *
\******************************************************************************/


/** Operation "__ns1__UpdateClassRoomPersonStatus" of service binding "UpdateStudentStatusSoap".

  - SOAP document/literal style messaging

  - Action: "JF.ClassRoomGuidance.Webservice/UpdateClassRoomPersonStatus"

  - Addressing input action: "JF.ClassRoomGuidance.Webservice/UpdateClassRoomPersonStatus"

  - Addressing output action: "JF.ClassRoomGuidance.Webservice/UpdateClassRoomPersonStatusResponse"

C stub function (defined in soapClient.c[pp] generated by soapcpp2):
@code
  int soap_call___ns1__UpdateClassRoomPersonStatus(
    struct soap *soap,
    NULL, // char *endpoint = NULL selects default endpoint for this operation
    NULL, // char *action = NULL selects default action for this operation
    // input parameters:
    _ns1__UpdateClassRoomPersonStatus*  ns1__UpdateClassRoomPersonStatus,
    // output parameters:
    _ns1__UpdateClassRoomPersonStatusResponse&ns1__UpdateClassRoomPersonStatusResponse
  );
@endcode

C server function (called from the service dispatcher defined in soapServer.c[pp]):
@code
  int __ns1__UpdateClassRoomPersonStatus(
    struct soap *soap,
    // input parameters:
    _ns1__UpdateClassRoomPersonStatus*  ns1__UpdateClassRoomPersonStatus,
    // output parameters:
    _ns1__UpdateClassRoomPersonStatusResponse&ns1__UpdateClassRoomPersonStatusResponse
  );
@endcode

C++ proxy class (defined in soapUpdateStudentStatusSoapProxy.h):
@code
  class UpdateStudentStatusSoapProxy;
@endcode
Important: use soapcpp2 option '-j' (or '-i') to generate improved and easy-to-use proxy classes;

C++ service class (defined in soapUpdateStudentStatusSoapService.h):
@code
  class UpdateStudentStatusSoapService;
@endcode
Important: use soapcpp2 option '-j' (or '-i') to generate improved and easy-to-use service classes;

*/

//gsoap ns1  service method-protocol:	UpdateClassRoomPersonStatus SOAP
//gsoap ns1  service method-style:	UpdateClassRoomPersonStatus document
//gsoap ns1  service method-encoding:	UpdateClassRoomPersonStatus literal
//gsoap ns1  service method-input-action:	UpdateClassRoomPersonStatus JF.ClassRoomGuidance.Webservice/UpdateClassRoomPersonStatus
//gsoap ns1  service method-output-action:	UpdateClassRoomPersonStatus JF.ClassRoomGuidance.Webservice/UpdateClassRoomPersonStatusResponse
int __ns1__UpdateClassRoomPersonStatus(
    _ns1__UpdateClassRoomPersonStatus*  ns1__UpdateClassRoomPersonStatus,	///< Input parameter
    _ns1__UpdateClassRoomPersonStatusResponse&ns1__UpdateClassRoomPersonStatusResponse	///< Output parameter
);

/******************************************************************************\
 *                                                                            *
 * Service Operation                                                          *
 *   __ns1__UpdateClassRoomPersonStatus_                                      *
 *                                                                            *
\******************************************************************************/


/** Operation "__ns1__UpdateClassRoomPersonStatus_" of service binding "UpdateStudentStatusSoap".

  - SOAP document/literal style messaging

  - Action: "JF.ClassRoomGuidance.Webservice/UpdateClassRoomPersonStatus"

  - Addressing input action: "JF.ClassRoomGuidance.Webservice/UpdateClassRoomPersonStatus"

  - Addressing output action: "JF.ClassRoomGuidance.Webservice/UpdateClassRoomPersonStatusResponse"

C stub function (defined in soapClient.c[pp] generated by soapcpp2):
@code
  int soap_call___ns1__UpdateClassRoomPersonStatus_(
    struct soap *soap,
    NULL, // char *endpoint = NULL selects default endpoint for this operation
    NULL, // char *action = NULL selects default action for this operation
    // input parameters:
    _ns1__UpdateClassRoomPersonStatus*  ns1__UpdateClassRoomPersonStatus,
    // output parameters:
    _ns1__UpdateClassRoomPersonStatusResponse&ns1__UpdateClassRoomPersonStatusResponse
  );
@endcode

C server function (called from the service dispatcher defined in soapServer.c[pp]):
@code
  int __ns1__UpdateClassRoomPersonStatus_(
    struct soap *soap,
    // input parameters:
    _ns1__UpdateClassRoomPersonStatus*  ns1__UpdateClassRoomPersonStatus,
    // output parameters:
    _ns1__UpdateClassRoomPersonStatusResponse&ns1__UpdateClassRoomPersonStatusResponse
  );
@endcode

C++ proxy class (defined in soapUpdateStudentStatusSoapProxy.h):
@code
  class UpdateStudentStatusSoapProxy;
@endcode
Important: use soapcpp2 option '-j' (or '-i') to generate improved and easy-to-use proxy classes;

C++ service class (defined in soapUpdateStudentStatusSoapService.h):
@code
  class UpdateStudentStatusSoapService;
@endcode
Important: use soapcpp2 option '-j' (or '-i') to generate improved and easy-to-use service classes;

*/

//gsoap ns1  service method-protocol:	UpdateClassRoomPersonStatus_ SOAP
//gsoap ns1  service method-style:	UpdateClassRoomPersonStatus_ document
//gsoap ns1  service method-encoding:	UpdateClassRoomPersonStatus_ literal
//gsoap ns1  service method-input-action:	UpdateClassRoomPersonStatus_ JF.ClassRoomGuidance.Webservice/UpdateClassRoomPersonStatus
//gsoap ns1  service method-output-action:	UpdateClassRoomPersonStatus_ JF.ClassRoomGuidance.Webservice/UpdateClassRoomPersonStatusResponse
int __ns1__UpdateClassRoomPersonStatus_(
    _ns1__UpdateClassRoomPersonStatus*  ns1__UpdateClassRoomPersonStatus,	///< Input parameter
    _ns1__UpdateClassRoomPersonStatusResponse&ns1__UpdateClassRoomPersonStatusResponse	///< Output parameter
);

/**

@page UpdateStudentStatusSoap Binding "UpdateStudentStatusSoap"

@section UpdateStudentStatusSoap_policy_enablers Policy Enablers of Binding "UpdateStudentStatusSoap"

None specified.

*/

/******************************************************************************\
 *                                                                            *
 * XML Data Binding                                                           *
 *                                                                            *
\******************************************************************************/


/**

@page page_XMLDataBinding XML Data Binding

SOAP/XML services use data bindings contractually bound by WSDL and auto-
generated by wsdl2h and soapcpp2 (see Service Bindings). Plain data bindings
are adopted from XML schemas as part of the WSDL types section or when running
wsdl2h on a set of schemas to produce non-SOAP-based XML data bindings.

The following readers and writers are C/C++ data type (de)serializers auto-
generated by wsdl2h and soapcpp2. Run soapcpp2 on this file to generate the
(de)serialization code, which is stored in soapC.c[pp]. Include "soapH.h" in
your code to import these data type and function declarations. Only use the
soapcpp2-generated files in your project build. Do not include the wsdl2h-
generated .h file in your code.

Data can be read in XML and deserialized from:
  - a file descriptor, using soap->recvfd = fd
  - a socket, using soap->socket = ...
  - a C++ stream, using soap->is = ...
  - a buffer, using the soap->frecv() callback

Data can be serialized in XML and written to:
  - a file descriptor, using soap->sendfd = fd
  - a socket, using soap->socket = ...
  - a C++ stream, using soap->os = ...
  - a buffer, using the soap->fsend() callback

The following options are available for (de)serialization control:
  - soap->encodingStyle = NULL; to remove SOAP 1.1/1.2 encodingStyle
  - soap_mode(soap, SOAP_XML_TREE); XML without id-ref (no cycles!)
  - soap_mode(soap, SOAP_XML_GRAPH); XML with id-ref (including cycles)
  - soap_set_namespaces(soap, struct Namespace *nsmap); to set xmlns bindings


@section ns1 Top-level root elements of schema "JF.ClassRoomGuidance.Webservice"

  - <UpdateClassRoomPersonStatus> @ref _ns1__UpdateClassRoomPersonStatus
    @code
    // Reader (returns SOAP_OK on success):
    soap_read__ns1__UpdateClassRoomPersonStatus(struct soap*, _ns1__UpdateClassRoomPersonStatus*);
    // Writer (returns SOAP_OK on success):
    soap_write__ns1__UpdateClassRoomPersonStatus(struct soap*, _ns1__UpdateClassRoomPersonStatus*);
    @endcode

  - <UpdateClassRoomPersonStatusResponse> @ref _ns1__UpdateClassRoomPersonStatusResponse
    @code
    // Reader (returns SOAP_OK on success):
    soap_read__ns1__UpdateClassRoomPersonStatusResponse(struct soap*, _ns1__UpdateClassRoomPersonStatusResponse*);
    // Writer (returns SOAP_OK on success):
    soap_write__ns1__UpdateClassRoomPersonStatusResponse(struct soap*, _ns1__UpdateClassRoomPersonStatusResponse*);
    @endcode

*/

/* End of doupload.h */
