/* soapStub.h
   Generated by gSOAP 2.8.23 from doupload.h

Copyright(C) 2000-2015, Robert van Engelen, Genivia Inc. All Rights Reserved.
The generated code is released under one of the following licenses:
GPL or Genivia's license for commercial use.
This program is released under the GPL with the additional exemption that
compiling, linking, and/or using OpenSSL is allowed.
*/

#ifndef soapStub_H
#define soapStub_H
#define SOAP_NAMESPACE_OF_ns1	"JF.ClassRoomGuidance.Webservice"
#include "stdsoap2.h"
#if GSOAP_VERSION != 20823
# error "GSOAP VERSION 20823 MISMATCH IN GENERATED CODE VERSUS LIBRARY CODE: PLEASE REINSTALL PACKAGE"
#endif


/******************************************************************************\
 *                                                                            *
 * Enumerations                                                               *
 *                                                                            *
\******************************************************************************/


/******************************************************************************\
 *                                                                            *
 * Types with Custom Serializers                                              *
 *                                                                            *
\******************************************************************************/


/******************************************************************************\
 *                                                                            *
 * Classes and Structs                                                        *
 *                                                                            *
\******************************************************************************/


#if 0 /* volatile type: do not declare here, declared elsewhere */

#endif

#ifndef SOAP_TYPE__ns1__UpdateClassRoomPersonStatus
#define SOAP_TYPE__ns1__UpdateClassRoomPersonStatus (7)
/* ns1:UpdateClassRoomPersonStatus */
class SOAP_CMAC _ns1__UpdateClassRoomPersonStatus
{
public:
	char *account;	/* optional element of type xsd:string */
	char *password;	/* optional element of type xsd:string */
	char *roomNo;	/* optional element of type xsd:string */
	int studentCount;	/* required element of type xsd:int */
	time_t updateTime;	/* required element of type xsd:dateTime */
	struct soap *soap;	/* transient */
public:
	virtual int soap_type() const { return 7; } /* = unique type id SOAP_TYPE__ns1__UpdateClassRoomPersonStatus */
	virtual void soap_default(struct soap*);
	virtual void soap_serialize(struct soap*) const;
	virtual int soap_put(struct soap*, const char*, const char*) const;
	virtual int soap_out(struct soap*, const char*, int, const char*) const;
	virtual void *soap_get(struct soap*, const char*, const char*);
	virtual void *soap_in(struct soap*, const char*, const char*);
	         _ns1__UpdateClassRoomPersonStatus() { _ns1__UpdateClassRoomPersonStatus::soap_default(NULL); }
	virtual ~_ns1__UpdateClassRoomPersonStatus() { }
};
#endif

#ifndef SOAP_TYPE__ns1__UpdateClassRoomPersonStatusResponse
#define SOAP_TYPE__ns1__UpdateClassRoomPersonStatusResponse (8)
/* ns1:UpdateClassRoomPersonStatusResponse */
class SOAP_CMAC _ns1__UpdateClassRoomPersonStatusResponse
{
public:
	int UpdateClassRoomPersonStatusResult;	/* SOAP 1.2 RPC return element (when namespace qualified) */	/* required element of type xsd:int */
	struct soap *soap;	/* transient */
public:
	virtual int soap_type() const { return 8; } /* = unique type id SOAP_TYPE__ns1__UpdateClassRoomPersonStatusResponse */
	virtual void soap_default(struct soap*);
	virtual void soap_serialize(struct soap*) const;
	virtual int soap_put(struct soap*, const char*, const char*) const;
	virtual int soap_out(struct soap*, const char*, int, const char*) const;
	virtual void *soap_get(struct soap*, const char*, const char*);
	virtual void *soap_in(struct soap*, const char*, const char*);
	         _ns1__UpdateClassRoomPersonStatusResponse() { _ns1__UpdateClassRoomPersonStatusResponse::soap_default(NULL); }
	virtual ~_ns1__UpdateClassRoomPersonStatusResponse() { }
};
#endif

#ifndef SOAP_TYPE___ns1__UpdateClassRoomPersonStatus
#define SOAP_TYPE___ns1__UpdateClassRoomPersonStatus (14)
/* Operation wrapper: */
struct __ns1__UpdateClassRoomPersonStatus
{
public:
	_ns1__UpdateClassRoomPersonStatus *ns1__UpdateClassRoomPersonStatus;	/* optional element of type ns1:UpdateClassRoomPersonStatus */
public:
	int soap_type() const { return 14; } /* = unique type id SOAP_TYPE___ns1__UpdateClassRoomPersonStatus */
};
#endif

#ifndef SOAP_TYPE___ns1__UpdateClassRoomPersonStatus_
#define SOAP_TYPE___ns1__UpdateClassRoomPersonStatus_ (16)
/* Operation wrapper: */
struct __ns1__UpdateClassRoomPersonStatus_
{
public:
	_ns1__UpdateClassRoomPersonStatus *ns1__UpdateClassRoomPersonStatus;	/* optional element of type ns1:UpdateClassRoomPersonStatus */
public:
	int soap_type() const { return 16; } /* = unique type id SOAP_TYPE___ns1__UpdateClassRoomPersonStatus_ */
};
#endif

#ifndef WITH_NOGLOBAL

#ifndef SOAP_TYPE_SOAP_ENV__Header
#define SOAP_TYPE_SOAP_ENV__Header (17)
/* SOAP Header: */
struct SOAP_ENV__Header
{
public:
	int soap_type() const { return 17; } /* = unique type id SOAP_TYPE_SOAP_ENV__Header */
};
#endif

#endif

#ifndef WITH_NOGLOBAL

#ifndef SOAP_TYPE_SOAP_ENV__Code
#define SOAP_TYPE_SOAP_ENV__Code (18)
/* SOAP Fault Code: */
struct SOAP_ENV__Code
{
public:
	char *SOAP_ENV__Value;	/* optional element of type xsd:QName */
	struct SOAP_ENV__Code *SOAP_ENV__Subcode;	/* optional element of type SOAP-ENV:Code */
public:
	int soap_type() const { return 18; } /* = unique type id SOAP_TYPE_SOAP_ENV__Code */
};
#endif

#endif

#ifndef WITH_NOGLOBAL

#ifndef SOAP_TYPE_SOAP_ENV__Detail
#define SOAP_TYPE_SOAP_ENV__Detail (20)
/* SOAP-ENV:Detail */
struct SOAP_ENV__Detail
{
public:
	char *__any;
	int __type;	/* any type of element <fault> (defined below) */
	void *fault;	/* transient */
public:
	int soap_type() const { return 20; } /* = unique type id SOAP_TYPE_SOAP_ENV__Detail */
};
#endif

#endif

#ifndef WITH_NOGLOBAL

#ifndef SOAP_TYPE_SOAP_ENV__Reason
#define SOAP_TYPE_SOAP_ENV__Reason (23)
/* SOAP-ENV:Reason */
struct SOAP_ENV__Reason
{
public:
	char *SOAP_ENV__Text;	/* optional element of type xsd:string */
public:
	int soap_type() const { return 23; } /* = unique type id SOAP_TYPE_SOAP_ENV__Reason */
};
#endif

#endif

#ifndef WITH_NOGLOBAL

#ifndef SOAP_TYPE_SOAP_ENV__Fault
#define SOAP_TYPE_SOAP_ENV__Fault (24)
/* SOAP Fault: */
struct SOAP_ENV__Fault
{
public:
	char *faultcode;	/* optional element of type xsd:QName */
	char *faultstring;	/* optional element of type xsd:string */
	char *faultactor;	/* optional element of type xsd:string */
	struct SOAP_ENV__Detail *detail;	/* optional element of type SOAP-ENV:Detail */
	struct SOAP_ENV__Code *SOAP_ENV__Code;	/* optional element of type SOAP-ENV:Code */
	struct SOAP_ENV__Reason *SOAP_ENV__Reason;	/* optional element of type SOAP-ENV:Reason */
	char *SOAP_ENV__Node;	/* optional element of type xsd:string */
	char *SOAP_ENV__Role;	/* optional element of type xsd:string */
	struct SOAP_ENV__Detail *SOAP_ENV__Detail;	/* optional element of type SOAP-ENV:Detail */
public:
	int soap_type() const { return 24; } /* = unique type id SOAP_TYPE_SOAP_ENV__Fault */
};
#endif

#endif

/******************************************************************************\
 *                                                                            *
 * Typedefs                                                                   *
 *                                                                            *
\******************************************************************************/

#ifndef SOAP_TYPE__QName
#define SOAP_TYPE__QName (5)
typedef char *_QName;
#endif

#ifndef SOAP_TYPE__XML
#define SOAP_TYPE__XML (6)
typedef char *_XML;
#endif


/******************************************************************************\
 *                                                                            *
 * Externals                                                                  *
 *                                                                            *
\******************************************************************************/


#endif

/* End of soapStub.h */
