/* soapUpdateStudentStatusSoapProxy.cpp
   Generated by gSOAP 2.8.23 from doupload.h

Copyright(C) 2000-2015, Robert van Engelen, Genivia Inc. All Rights Reserved.
The generated code is released under one of the following licenses:
GPL or Genivia's license for commercial use.
This program is released under the GPL with the additional exemption that
compiling, linking, and/or using OpenSSL is allowed.
*/

#include "soapUpdateStudentStatusSoapProxy.h"

UpdateStudentStatusSoapProxy::UpdateStudentStatusSoapProxy() : soap(SOAP_IO_DEFAULT)
{	UpdateStudentStatusSoapProxy_init(SOAP_IO_DEFAULT, SOAP_IO_DEFAULT);
}

UpdateStudentStatusSoapProxy::UpdateStudentStatusSoapProxy(const struct soap &_soap) : soap(_soap)
{ }

UpdateStudentStatusSoapProxy::UpdateStudentStatusSoapProxy(const char *url) : soap(SOAP_IO_DEFAULT)
{	UpdateStudentStatusSoapProxy_init(SOAP_IO_DEFAULT, SOAP_IO_DEFAULT);
	soap_endpoint = url;
}

UpdateStudentStatusSoapProxy::UpdateStudentStatusSoapProxy(soap_mode iomode) : soap(iomode)
{	UpdateStudentStatusSoapProxy_init(iomode, iomode);
}

UpdateStudentStatusSoapProxy::UpdateStudentStatusSoapProxy(const char *url, soap_mode iomode) : soap(iomode)
{	UpdateStudentStatusSoapProxy_init(iomode, iomode);
	soap_endpoint = url;
}

UpdateStudentStatusSoapProxy::UpdateStudentStatusSoapProxy(soap_mode imode, soap_mode omode) : soap(imode, omode)
{	UpdateStudentStatusSoapProxy_init(imode, omode);
}

UpdateStudentStatusSoapProxy::~UpdateStudentStatusSoapProxy()
{
	this->destroy();
	}

void UpdateStudentStatusSoapProxy::UpdateStudentStatusSoapProxy_init(soap_mode imode, soap_mode omode)
{	soap_imode(this, imode);
	soap_omode(this, omode);
	soap_endpoint = NULL;
	static const struct Namespace namespaces[] =
{
	{"SOAP-ENV", "http://www.w3.org/2003/05/soap-envelope", "http://schemas.xmlsoap.org/soap/envelope/", NULL},
	{"SOAP-ENC", "http://www.w3.org/2003/05/soap-encoding", "http://schemas.xmlsoap.org/soap/encoding/", NULL},
	{"xsi", "http://www.w3.org/2001/XMLSchema-instance", "http://www.w3.org/*/XMLSchema-instance", NULL},
	{"xsd", "http://www.w3.org/2001/XMLSchema", "http://www.w3.org/*/XMLSchema", NULL},
	{"ns1", "JF.ClassRoomGuidance.Webservice", NULL, NULL},
	{NULL, NULL, NULL, NULL}
};
	soap_set_namespaces(this, namespaces);
}

void UpdateStudentStatusSoapProxy::destroy()
{	soap_destroy(this);
	soap_end(this);
}

void UpdateStudentStatusSoapProxy::reset()
{	this->destroy();
	soap_done(this);
	soap_initialize(this);
	UpdateStudentStatusSoapProxy_init(SOAP_IO_DEFAULT, SOAP_IO_DEFAULT);
}

void UpdateStudentStatusSoapProxy::soap_noheader()
{	this->header = NULL;
}

const SOAP_ENV__Header *UpdateStudentStatusSoapProxy::soap_header()
{	return this->header;
}

const SOAP_ENV__Fault *UpdateStudentStatusSoapProxy::soap_fault()
{	return this->fault;
}

const char *UpdateStudentStatusSoapProxy::soap_fault_string()
{	return *soap_faultstring(this);
}

const char *UpdateStudentStatusSoapProxy::soap_fault_detail()
{	return *soap_faultdetail(this);
}

int UpdateStudentStatusSoapProxy::soap_close_socket()
{	return soap_closesock(this);
}

int UpdateStudentStatusSoapProxy::soap_force_close_socket()
{	return soap_force_closesock(this);
}

void UpdateStudentStatusSoapProxy::soap_print_fault(FILE *fd)
{	::soap_print_fault(this, fd);
}

#ifndef WITH_LEAN
#ifndef WITH_COMPAT
void UpdateStudentStatusSoapProxy::soap_stream_fault(std::ostream& os)
{	::soap_stream_fault(this, os);
}
#endif

char *UpdateStudentStatusSoapProxy::soap_sprint_fault(char *buf, size_t len)
{	return ::soap_sprint_fault(this, buf, len);
}
#endif

int UpdateStudentStatusSoapProxy::UpdateClassRoomPersonStatus(const char *endpoint, const char *soap_action, _ns1__UpdateClassRoomPersonStatus *ns1__UpdateClassRoomPersonStatus, _ns1__UpdateClassRoomPersonStatusResponse &ns1__UpdateClassRoomPersonStatusResponse)
{	struct soap *soap = this;
	struct __ns1__UpdateClassRoomPersonStatus soap_tmp___ns1__UpdateClassRoomPersonStatus;
	if (endpoint)
		soap_endpoint = endpoint;
	if (soap_endpoint == NULL)
		soap_endpoint = "http://cqjunfa.xicp.cn:5678/UpdateStudentStatus.asmx";
	if (soap_action == NULL)
		soap_action = "JF.ClassRoomGuidance.Webservice/UpdateClassRoomPersonStatus";
	soap_begin(soap);
	soap->encodingStyle = NULL;
	soap_tmp___ns1__UpdateClassRoomPersonStatus.ns1__UpdateClassRoomPersonStatus = ns1__UpdateClassRoomPersonStatus;
	soap_serializeheader(soap);
	soap_serialize___ns1__UpdateClassRoomPersonStatus(soap, &soap_tmp___ns1__UpdateClassRoomPersonStatus);
	if (soap_begin_count(soap))
		return soap->error;
	if (soap->mode & SOAP_IO_LENGTH)
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || soap_put___ns1__UpdateClassRoomPersonStatus(soap, &soap_tmp___ns1__UpdateClassRoomPersonStatus, "-ns1:UpdateClassRoomPersonStatus", NULL)
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	}
	if (soap_end_count(soap))
		return soap->error;
	if (soap_connect(soap, soap_url(soap, soap_endpoint, NULL), soap_action)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || soap_put___ns1__UpdateClassRoomPersonStatus(soap, &soap_tmp___ns1__UpdateClassRoomPersonStatus, "-ns1:UpdateClassRoomPersonStatus", NULL)
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap_closesock(soap);
	if (!&ns1__UpdateClassRoomPersonStatusResponse)
		return soap_closesock(soap);
	ns1__UpdateClassRoomPersonStatusResponse.soap_default(soap);
	if (soap_begin_recv(soap)
	 || soap_envelope_begin_in(soap)
	 || soap_recv_header(soap)
	 || soap_body_begin_in(soap))
		return soap_closesock(soap);
	ns1__UpdateClassRoomPersonStatusResponse.soap_get(soap, "ns1:UpdateClassRoomPersonStatusResponse", NULL);
	if (soap->error)
		return soap_recv_fault(soap, 0);
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap_closesock(soap);
	return soap_closesock(soap);
}

int UpdateStudentStatusSoapProxy::UpdateClassRoomPersonStatus_(const char *endpoint, const char *soap_action, _ns1__UpdateClassRoomPersonStatus *ns1__UpdateClassRoomPersonStatus, _ns1__UpdateClassRoomPersonStatusResponse &ns1__UpdateClassRoomPersonStatusResponse)
{	struct soap *soap = this;
	struct __ns1__UpdateClassRoomPersonStatus_ soap_tmp___ns1__UpdateClassRoomPersonStatus_;
	if (endpoint)
		soap_endpoint = endpoint;
	if (soap_endpoint == NULL)
		soap_endpoint = "http://cqjunfa.xicp.cn:5678/UpdateStudentStatus.asmx";
	if (soap_action == NULL)
		soap_action = "JF.ClassRoomGuidance.Webservice/UpdateClassRoomPersonStatus";
	soap_begin(soap);
	soap->encodingStyle = NULL;
	soap_tmp___ns1__UpdateClassRoomPersonStatus_.ns1__UpdateClassRoomPersonStatus = ns1__UpdateClassRoomPersonStatus;
	soap_serializeheader(soap);
	soap_serialize___ns1__UpdateClassRoomPersonStatus_(soap, &soap_tmp___ns1__UpdateClassRoomPersonStatus_);
	if (soap_begin_count(soap))
		return soap->error;
	if (soap->mode & SOAP_IO_LENGTH)
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || soap_put___ns1__UpdateClassRoomPersonStatus_(soap, &soap_tmp___ns1__UpdateClassRoomPersonStatus_, "-ns1:UpdateClassRoomPersonStatus", NULL)
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	}
	if (soap_end_count(soap))
		return soap->error;
	if (soap_connect(soap, soap_url(soap, soap_endpoint, NULL), soap_action)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || soap_put___ns1__UpdateClassRoomPersonStatus_(soap, &soap_tmp___ns1__UpdateClassRoomPersonStatus_, "-ns1:UpdateClassRoomPersonStatus", NULL)
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap_closesock(soap);
	if (!&ns1__UpdateClassRoomPersonStatusResponse)
		return soap_closesock(soap);
	ns1__UpdateClassRoomPersonStatusResponse.soap_default(soap);
	if (soap_begin_recv(soap)
	 || soap_envelope_begin_in(soap)
	 || soap_recv_header(soap)
	 || soap_body_begin_in(soap))
		return soap_closesock(soap);
	ns1__UpdateClassRoomPersonStatusResponse.soap_get(soap, "ns1:UpdateClassRoomPersonStatusResponse", NULL);
	if (soap->error)
		return soap_recv_fault(soap, 0);
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap_closesock(soap);
	return soap_closesock(soap);
}
/* End of client proxy code */
